[profile.default]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
optimizer = true
optimizer_runs = 100000

# pre push0 for maximum compatibility
evm_version = "paris"

remappings = [
    "rain.factory/=lib/rain.factory/src/",
    "rain.interpreter.interface/=lib/rain.interpreter.interface/src/",
]

bytecode_hash = "none"
cbor_metadata = false